In [1]:
import nltk
import pandas as pd

In [2]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\ayuku\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [3]:
fake=pd.read_csv("C:/Users/ayuku/Downloads/Fake.csv")
genuine = pd.read_csv("C:/Users/ayuku/Downloads/True.csv")

In [4]:
genuine

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"
...,...,...,...,...
21412,'Fully committed' NATO backs new U.S. approach...,BRUSSELS (Reuters) - NATO allies on Tuesday we...,worldnews,"August 22, 2017"
21413,LexisNexis withdrew two products from Chinese ...,"LONDON (Reuters) - LexisNexis, a provider of l...",worldnews,"August 22, 2017"
21414,Minsk cultural hub becomes haven from authorities,MINSK (Reuters) - In the shadow of disused Sov...,worldnews,"August 22, 2017"
21415,Vatican upbeat on possibility of Pope Francis ...,MOSCOW (Reuters) - Vatican Secretary of State ...,worldnews,"August 22, 2017"
21416,Indonesia to buy $1.14 billion worth of Russia...,JAKARTA (Reuters) - Indonesia will buy 11 Sukh...,worldnews,"August 22, 2017"

In [5]:
fake['genuiness']=0
genuine['genuiness']=1

In [6]:
genuine

,title,text,subject,date,genuiness
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017",1
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017",1
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017",1
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017",1
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017",1
...,...,...,...,...,...
21412,'Fully committed' NATO backs new U.S. approach...,BRUSSELS (Reuters) - NATO allies on Tuesday we...,worldnews,"August 22, 2017",1
21413,LexisNexis withdrew two products from Chinese ...,"LONDON (Reuters) - LexisNexis, a provider of l...",worldnews,"August 22, 2017",1
21414,Minsk cultural hub becomes haven from authorities,MINSK (Reuters) - In the shadow of disused Sov...,worldnews,"August 22, 2017",1
21415,Vatican upbeat on possibility of Pope Francis ...,MOSCOW (Reuters) - Vatican Secretary of State ...,worldnews,"August 22, 2017",1
21416,Indonesia to buy $1.14 billion worth of Russia...,JAKARTA (Reuters) - Indonesia will buy 11 Sukh...,worldnews,"August 22, 2017",1

In [7]:
dataset=pd.concat([fake,genuine])

In [8]:
dataset

,title,text,subject,date,genuiness
0,Donald Trump Sends Out Embarrassing New Yearâ€™...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0
3,Trump Is So Obsessed He Even Has Obamaâ€™s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",0
...,...,...,...,...,...
21412,'Fully committed' NATO backs new U.S. approach...,BRUSSELS (Reuters) - NATO allies on Tuesday we...,worldnews,"August 22, 2017",1
21413,LexisNexis withdrew two products from Chinese ...,"LONDON (Reuters) - LexisNexis, a provider of l...",worldnews,"August 22, 2017",1
21414,Minsk cultural hub becomes haven from authorities,MINSK (Reuters) - In the shadow of disused Sov...,worldnews,"August 22, 2017",1
21415,Vatican upbeat on possibility of Pope Francis ...,MOSCOW (Reuters) - Vatican Secretary of State ...,worldnews,"August 22, 2017",1
21416,Indonesia to buy $1.14 billion worth of Russia...,JAKARTA (Reuters) - Indonesia will buy 11 Sukh...,worldnews,"August 22, 2017",1

## Pre Processing

In [9]:
dataset = dataset.reset_index(drop=True)

In [10]:
dataset

,title,text,subject,date,genuiness
0,Donald Trump Sends Out Embarrassing New Yearâ€™...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0
3,Trump Is So Obsessed He Even Has Obamaâ€™s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",0
...,...,...,...,...,...
44893,'Fully committed' NATO backs new U.S. approach...,BRUSSELS (Reuters) - NATO allies on Tuesday we...,worldnews,"August 22, 2017",1
44894,LexisNexis withdrew two products from Chinese ...,"LONDON (Reuters) - LexisNexis, a provider of l...",worldnews,"August 22, 2017",1
44895,Minsk cultural hub becomes haven from authorities,MINSK (Reuters) - In the shadow of disused Sov...,worldnews,"August 22, 2017",1
44896,Vatican upbeat on possibility of Pope Francis ...,MOSCOW (Reuters) - Vatican Secretary of State ...,worldnews,"August 22, 2017",1
44897,Indonesia to buy $1.14 billion worth of Russia...,JAKARTA (Reuters) - Indonesia will buy 11 Sukh...,worldnews,"August 22, 2017",1

In [11]:
dataset = dataset.drop(['date','title','subject'],axis=1)

In [12]:
dataset

                                                    text  genuiness
0      Donald Trump just couldn t wish all Americans ...          0
1      House Intelligence Committee Chairman Devin Nu...          0
2      On Friday, it was revealed that former Milwauk...          0
3      On Christmas day, Donald Trump announced that ...          0
4      Pope Francis used his annual Christmas Day mes...          0
...                                                  ...        ...
44893  BRUSSELS (Reuters) - NATO allies on Tuesday we...          1
44894  LONDON (Reuters) - LexisNexis, a provider of l...          1
44895  MINSK (Reuters) - In the shadow of disused Sov...          1
44896  MOSCOW (Reuters) - Vatican Secretary of State ...          1
44897  JAKARTA (Reuters) - Indonesia will buy 11 Sukh...          1

[44898 rows x 2 columns]

In [13]:
from nltk.tokenize import word_tokenize
dataset['text'] = dataset['text'].apply(word_tokenize)

In [14]:
dataset

                                                    text  genuiness
0      [Donald, Trump, just, couldn, t, wish, all, Am...          0
1      [House, Intelligence, Committee, Chairman, Dev...          0
2      [On, Friday, ,, it, was, revealed, that, forme...          0
3      [On, Christmas, day, ,, Donald, Trump, announc...          0
4      [Pope, Francis, used, his, annual, Christmas, ...          0
...                                                  ...        ...
44893  [BRUSSELS, (, Reuters, ), -, NATO, allies, on,...          1
44894  [LONDON, (, Reuters, ), -, LexisNexis, ,, a, p...          1
44895  [MINSK, (, Reuters, ), -, In, the, shadow, of,...          1
44896  [MOSCOW, (, Reuters, ), -, Vatican, Secretary,...          1
44897  [JAKARTA, (, Reuters, ), -, Indonesia, will, b...          1

[44898 rows x 2 columns]

In [15]:
from nltk.stem.snowball import SnowballStemmer

In [16]:
sb = SnowballStemmer('english')

In [17]:
def stem_it(text):
    return [sb.stem(word) for word in text]

In [18]:
dataset['text'] = dataset['text'].apply(stem_it)

In [19]:
dataset

                                                    text  genuiness
0      [donald, trump, just, couldn, t, wish, all, am...          0
1      [hous, intellig, committe, chairman, devin, nu...          0
2      [on, friday, ,, it, was, reveal, that, former,...          0
3      [on, christma, day, ,, donald, trump, announc,...          0
4      [pope, franci, use, his, annual, christma, day...          0
...                                                  ...        ...
44893  [brussel, (, reuter, ), -, nato, alli, on, tue...          1
44894  [london, (, reuter, ), -, lexisnexi, ,, a, pro...          1
44895  [minsk, (, reuter, ), -, in, the, shadow, of, ...          1
44896  [moscow, (, reuter, ), -, vatican, secretari, ...          1
44897  [jakarta, (, reuter, ), -, indonesia, will, bu...          1

[44898 rows x 2 columns]

In [20]:
def stopword_revomal(text):
    return [word for word in text if len(word)>>2]

In [21]:
dataset['text'] = dataset['text'].apply(stopword_revomal)

In [22]:
dataset

                                                    text  genuiness
0      [donald, trump, just, couldn, wish, american, ...          0
1      [hous, intellig, committe, chairman, devin, nu...          0
2      [friday, reveal, that, former, milwauke, sheri...          0
3      [christma, donald, trump, announc, that, would...          0
4      [pope, franci, annual, christma, messag, rebuk...          0
...                                                  ...        ...
44893  [brussel, reuter, nato, alli, tuesday, welcom,...          1
44894  [london, reuter, lexisnexi, provid, legal, reg...          1
44895  [minsk, reuter, shadow, disus, soviet-era, fac...          1
44896  [moscow, reuter, vatican, secretari, state, ca...          1
44897  [jakarta, reuter, indonesia, will, sukhoi, fig...          1

[44898 rows x 2 columns]

In [23]:
dataset['text'] = dataset['text'].apply(' '.join)

In [24]:
dataset

                                                    text  genuiness
0      donald trump just couldn wish american happi y...          0
1      hous intellig committe chairman devin nune hav...          0
2      friday reveal that former milwauke sheriff dav...          0
3      christma donald trump announc that would back ...          0
4      pope franci annual christma messag rebuk donal...          0
...                                                  ...        ...
44893  brussel reuter nato alli tuesday welcom presid...          1
44894  london reuter lexisnexi provid legal regulator...          1
44895  minsk reuter shadow disus soviet-era factori m...          1
44896  moscow reuter vatican secretari state cardin p...          1
44897  jakarta reuter indonesia will sukhoi fighter w...          1

[44898 rows x 2 columns]

In [25]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(dataset['text'],dataset['genuiness'],test_size=0.25)

In [26]:
x_train

11240    russia gave john podesta million dollar billio...
38468    manila reuter u.s. presid donald trump briefli...
14497    rampant migrant rape violenc shine light progr...
22778    this stori about trust mainstream media outlet...
21700    come town near sign hung public squar antwerp ...
                               ...
10688    london muslim mayor sadiq khan call british go...
2870     tuesday announc that donald trump elect keep j...
39423    london reuter prime minist theresa said wednes...
30843    london reuter u.s. president-elect donald trum...
25251    washington reuter u.s. congression leader whit...
Name: text, Length: 33673, dtype: object

In [27]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidfv = TfidfVectorizer(max_df = 0.7)

In [28]:
tfidfv_train = tfidfv.fit_transform(x_train)
tfidfv_test = tfidfv.transform(x_test)

In [29]:
print(tfidfv_train)

  (0, 2399)	0.1692925964900776
  (0, 50914)	0.15962163911133104
  (0, 12765)	0.4395780922622423
  (0, 12752)	0.15097330383386748
  (0, 18595)	0.4395780922622423
  (0, 20762)	0.14445578602783296
  (0, 82257)	0.1282715974143039
  (0, 62418)	0.16237170209862595
  (0, 58646)	0.11381624796811877
  (0, 12519)	0.14233182487254104
  (0, 20180)	0.1273039433349862
  (0, 38146)	0.12712578082084605
  (0, 7792)	0.16730040583526629
  (0, 86921)	0.10538866749933273
  (0, 69615)	0.3802868197437213
  (0, 14172)	0.16244174638028785
  (0, 26202)	0.17455308949886753
  (0, 53385)	0.12542031151191066
  (0, 63118)	0.27865671838345535
  (0, 43260)	0.15188188089864463
  (0, 33583)	0.16878633613309119
  (0, 69802)	0.14777585185415326
  (1, 70542)	0.11590668296001946
  (1, 70697)	0.13991921540874275
  (1, 40025)	0.09840868632670899
  :	:
  (33672, 72230)	0.21568228949094556
  (33672, 60063)	0.2509297227135464
  (33672, 32364)	0.28264218368761557
  (33672, 31317)	0.24137951461132595
  (33672, 58859)	0.1905999425791168
  (33672, 53108)	0.24591847910984663
  (33672, 21316)	0.36589313567169596
  (33672, 67213)	0.18142429814988728
  (33672, 16452)	0.19404333321418152
  (33672, 26104)	0.1836785129389229
  (33672, 75170)	0.3137219143377697
  (33672, 67481)	0.15027988384931748
  (33672, 21312)	0.14731502824507503
  (33672, 34676)	0.20630471097569056
  (33672, 86479)	0.11147715949579494
  (33672, 58993)	0.11649009863007971
  (33672, 87232)	0.08210666307864609
  (33672, 86139)	0.11062821852530769
  (33672, 86470)	0.13522624144099774
  (33672, 64395)	0.16739900833315485
  (33672, 27186)	0.11464867569681658
  (33672, 39024)	0.10712113030253613
  (33672, 86978)	0.11695271983080568
  (33672, 47601)	0.12366915487150133
  (33672, 68167)	0.08319777061252745

In [30]:
from sklearn.linear_model import LogisticRegression

In [31]:
lr = LogisticRegression(max_iter = 1000)
lr.fit(tfidfv_train,y_train)

LogisticRegression(max_iter=1000)

In [32]:
y_pred = lr.predict(tfidfv_test)

In [33]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.9876169265033408

In [34]:
from sklearn.linear_model import PassiveAggressiveClassifier

pac = PassiveAggressiveClassifier(max_iter = 100)
pac.fit(tfidfv_train,y_train)

PassiveAggressiveClassifier(max_iter=100)

In [35]:
y_pred_pac = pac.predict(tfidfv_test)
accuracy_score(y_test,y_pred_pac)

0.9965256124721603